### ISSUE TITLE
Pasos para montar el ambiente de desarrollo

### ISSUE THREAD

**Issue by D3vlin** [lncgomz/anarvistaweb#1]
Hola hermano, intente correr tu proyecto, abrí el index pero no ocurrió nada más allá de indicarme que escaneara un marcador, me puedes dejar los pasos para ejecutarlo bien

**Comment by lncgomz** [comment]
El navegador desde donde lo estés ejecutando debería pedirte permiso para utilizar la cámara, luego debes enfocar alguno de los marcadores y ya con eso debe mostrarte la animación en realidad aumentada.

**Comment by D3vlin** [comment]
Para trabarlo en ambiente desarrollo después de clonarse el repositorio se deben correr dos comandos desde la terminal estando en la carpeta del proyecto.

Instalar servidor local: npm install -g live-server
Correr servidor local: live-server
