### ISSUE TITLE
Aportes

### ISSUE THREAD

**Issue by D3vlin** [lncgomz/anarvistaweb#2]
Estaba planeando como hacer progresar el proyecto pero me surgieron más dudas.

Aparte de las librerías que estas implementando, que frameworks o estructura del proyecto sigues y que features hacen falta por implementar.

Puedes aportarme más sobre la visión del proyecto, así tendré claro como proceder.

**Comment by lncgomz** [comment]
Se está utilizando AR.js y Three.json, estas librerías no se integran bien con Angular, un feature deseable sería lograr esa integración, se intentó con la librería AR.js disponible para Angular pero al momento de ejecutarse, falla.

**Comment by D3vlin** [comment]
Ok, intentaré partir con otra rama donde probar integrarlo con angular ya que le daría mucho potencial de expansión

**Comment by D3vlin** [comment]
He logrado avanzar con Angular, integre la librería y aunque me pide el permiso de la cámara y lo doy, no me muestra la imagen, aunque lo hace por menos de un segundo como si titilara antes de no mostrar nada.

Que error tenías tú?

**Comment by lncgomz** [comment]
Estaba teniendo problemas llevando a cabo esa integracion, la cámara no llegaba a arrancar, es normal que pida autorización para usar la cámara del browser o el teléfono

**Comment by D3vlin** [comment]
Voy a continuar intentándolo con Angular, pero veré dejando el Iframe como lo tienes

**Comment by lncgomz** [comment]
He ido agregando más modelos al código, creo que en este punto deberíamos integrar los cambios, así sea en otra rama

**Comment by D3vlin** [comment]
Tengo una rama aparte donde estoy probando el angular, así no afecto la rama inicial desde donde partí el fork

**Comment by D3vlin** [comment]
Bueno he estado luchando, he conseguido algo de avance y asta ahora he llegado a este error que no he comprendido como solucionar...

![image](https://user-images.githubusercontent.com/46509440/235361711-1f40186f-71c1-4318-97b8-5758fad781cd.png)


Tienes alguna idea de la causa?
